/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package facturacion;

import Conexion.ConexionBD;
import Conexion.ConexionConsultas;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANDRES
 */
public class Interfaz_buscarclientes extends javax.swing.JInternalFrame {

    ConexionBD mysql = new ConexionBD(); 
    Connection conect= mysql.conectar(); 
    private Object[][] datostabla;    
    control_existencias ctr = new control_existencias();
    public Interfaz_buscarclientes() {
        initComponents();
//        mostrar_tabla();
        mostrarDatos();
    }
              
    
//     public void mostrar_tabla(){
//        control_cliente control = new control_cliente("Documento","Tipo de documento","Nombres","Apellidos","Direccion","Ciudad","telefono");       
//        String[] columnas = {"Documento","Tipo de documento","Nombres","Apellidos","Direccion","Ciudad","Telefono"};
//        datostabla = control.consulta_clientes();
//        DefaultTableModel datos = new DefaultTableModel(datostabla,columnas);
//        
//        
//        
//        jTable1.setModel(datos);
//
//
//}
    public void mostrarDatos(){
        DefaultTableModel tcliente = new DefaultTableModel();
        tcliente.addColumn("Num_Documento");
        tcliente.addColumn("Documento");
        tcliente.addColumn("Nombres");
        tcliente.addColumn("Apellido");
        tcliente.addColumn("Direccion");
        tcliente.addColumn("Ciudad");
        tcliente.addColumn("Telefono");
        jTable1.setModel(tcliente);
//        buscarcliente.getText();
//        Object selectedItem = ComboBoxBuscar.getSelectedItem();
//        String item = (String) ComboBoxBuscar.getSelectedItem();
//        
        String [] datos = new String[8];

        try {
            Statement leer = conect.createStatement();
            ResultSet resultado = leer.executeQuery("SELECT * FROM cliente");

            
            while(resultado.next()){
                datos[0] = resultado.getString(1);
                datos[1] = resultado.getString(2);
                datos[2] = resultado.getString(3);
                datos[3] = resultado.getString(4);
                datos[4] = resultado.getString(5);
                datos[5] = resultado.getString(6);
                datos[6] = resultado.getString(7);
//                datos[7] = resultado.getString(8);
//                datos[8] = resultado.getString(9);
                tcliente.addRow(datos);
            }

            jTable1.setModel(tcliente);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e +  "Error en la consulta");
        }
    }
     
     
     public ResultSet SeleccionarDatos(String nombre){
        DefaultTableModel tcliente = new DefaultTableModel();
          tcliente.addColumn("Num_Documento");
        tcliente.addColumn("Documento");
        tcliente.addColumn("Nombres");
        tcliente.addColumn("Apellido");
        tcliente.addColumn("Direccion");
        tcliente.addColumn("Ciudad");
        tcliente.addColumn("Telefono");
        jTable1.setModel(tcliente);
//        buscarcliente.getText();
//        Object selectedItem = ComboBoxBuscar.getSelectedItem();
        
        String combo ;
//        combo = ComboBoxBuscar.getItemAt(ComboBoxBuscar.getSelectedIndex()).getCodigo();

        String [] datos = new String[7];
        ConexionBD mysql = new ConexionBD(); 
           mysql.conectar();
           Connection cn=mysql.conectar();
        try {

            Statement leer = conect.createStatement();
            ResultSet resultado = leer.executeQuery("SELECT * FROM cliente");
            while(resultado.next()){
                    datos[0] = resultado.getString(1);
                datos[1] = resultado.getString(2);
                datos[2] = resultado.getString(3);
                datos[3] = resultado.getString(4);
                datos[4] = resultado.getString(5);
                datos[5] = resultado.getString(6);
                datos[6] = resultado.getString(7);
                tcliente.addRow(datos);
            }
            jTable1.setModel(tcliente);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e +  "Error en la consulta");
        }
        return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar clientes");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
